version: "3.8"

services:
    db:
        image: postgres
        container_name: postgresql
        environment:
            - POSTGRES_DB=PrismaExample
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        container_name: Adminpg
        ports:
            - 5050:80
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: example@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
